# Generated by Django 4.0 on 2022-01-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('cate', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pric', models.PositiveSmallIntegerField(default=0)),
                ('cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techno360.category')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open', models.BooleanField()),
                ('cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='techno360.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fnam', models.CharField(max_length=75)),
                ('lnam', models.CharField(max_length=75)),
                ('mail', models.CharField(max_length=125)),
                ('phon', models.CharField(blank=True, max_length=15, null=True)),
                ('join', models.DateTimeField(auto_now_add=True)),
                ('actv', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('frmu', models.BooleanField()),
                ('thrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno360.thread')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno360.user'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cret', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DateTimeField(blank=True, null=True)),
                ('dliv', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='techno360.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno360.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SlugField()),
                ('rate', models.BooleanField()),
                ('desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno360.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contractual',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('pric', models.PositiveIntegerField()),
                ('cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techno360.category')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='techno360.contractual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno360.user')),
            ],
        ),
    ]
